### PR TITLE
fix for issue #107

### PR DESCRIPTION
**Pull request by abbbi**
see issue #107

### CODE REVIEW

**Comment by pvital** [comment]
Hello @abbbi 

Thanks by your contribution, but Wok don't accept Pull Requests. Please, follow the instructions in https://github.com/kimchi-project/wok/wiki/How-to-Contribute and submit your patch to the mailing list to be reviewed.

I checked your patch and it looks good. Just guarantee that your changes will also build wok on Fedora and OpenSuse. Follow the steps to contribute a we'll be glad to commit your patch.

Thanks and best regards.

**Comment by abbbi** [comment]
Hi,
i will not forward the pull request to the mailinglist as i dont want to subscribe :)

**Comment by cwittmer** [comment]
@pvital 
why don't you send pull requests automatically to the ML?

**Comment by evansharp** [comment]
> Wok don't accept Pull Requests

This might be the stupidest thing I've ever read on Github. What's the point of using the platform if you're not going to take advantage of _volunteer_ contributors giving their time to _help your project_ by making it easy for them? A _mailing list_ for review? What is this, the 90s?

@abbbi, good for you not jumping through this hoop. I wouldn't want to subscribe either. If they want your effort, they should have to do this properly.

**Comment by pvital** [comment]
@evansharp I completely agree with you. All the other projects I (co-)maintain in GitHub are using the PullRequest feature and we also do code review there. However, this is a project decision and it's not in my (and others) control. :-(

**Comment by evansharp** [comment]
@pvital Well that's just too bad for them.

**Comment by alinefm** [comment]
The issue #107 was already fixed. Closing this PR.

**Pull request closed without merging**
